/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gdrwarhammer40k;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author 39340
 */
public class SchermataGioco extends javax.swing.JFrame {

    /**
     * Creates new form SchermataInizio
     */
        
    
        GestoreGioco gg;
        
        ImageIcon tf = new javax.swing.ImageIcon(getClass().getResource("/imagini/Capillary_Towers.jpg"));
        Image TyranidFieldIcon = tf.getImage().getScaledInstance(1600, 900,  Image.SCALE_SMOOTH);        
        ImageIcon nhw = new javax.swing.ImageIcon(getClass().getResource("/imagini/Necron-Homeworld.jpg"));
        Image NecronTombWorldIcon = nhw.getImage().getScaledInstance(1400, 700,  Image.SCALE_SMOOTH);        
        ImageIcon CD = new javax.swing.ImageIcon(getClass().getResource("/imagini/ChaosDomain.png"));
        Image ChaosDomainIcon = CD.getImage().getScaledInstance(1600, 900,  Image.SCALE_SMOOTH);
    
        
        ImageIcon TyranidField = new ImageIcon(TyranidFieldIcon);
        ImageIcon NecronTombWorld = new ImageIcon(NecronTombWorldIcon);
        ImageIcon ChaosDomain = new ImageIcon(ChaosDomainIcon);
        
    public SchermataGioco() {
        initComponents();  

    }
    void startRound(){
        ImageIcon playerSrc = new javax.swing.ImageIcon(getClass().getResource(gg.getGiocatore().getImgFile()));
        Image playerImgScale = playerSrc.getImage().getScaledInstance(gg.getGiocatore().getLar()*3/2, gg.getGiocatore().getAlt()*3/2,  Image.SCALE_SMOOTH); 
        ImageIcon player = new ImageIcon(playerImgScale);
        personaggio.setIcon(player);
        
        sfondo.setIcon(TyranidField);
        setContentPane(sfondo);
        
        sfondo.add(this.Necron);
        sfondo.add(this.Tyranids);
        sfondo.add(this.chaos);
        sfondo.add(this.personaggio);
    }

    void setGG(GestoreGioco gegio){
        gg = gegio;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sfondo = new javax.swing.JLabel();
        Tyranids = new javax.swing.JButton();
        chaos = new javax.swing.JButton();
        Necron = new javax.swing.JButton();
        personaggio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(sfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(692, 6, -1, -1));

        Tyranids.setText("tyranids");
        Tyranids.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TyranidsActionPerformed(evt);
            }
        });
        getContentPane().add(Tyranids, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 37, -1, -1));

        chaos.setText("Chaos");
        chaos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chaosActionPerformed(evt);
            }
        });
        getContentPane().add(chaos, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 72, -1, -1));

        Necron.setText("Necron");
        Necron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NecronActionPerformed(evt);
            }
        });
        getContentPane().add(Necron, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 107, -1, -1));
        getContentPane().add(personaggio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 560, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TyranidsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TyranidsActionPerformed
        // TODO add your handling code here:
        sfondo.setIcon(TyranidField);
        setContentPane(sfondo);
    }//GEN-LAST:event_TyranidsActionPerformed

    private void chaosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chaosActionPerformed
        // TODO add your handling code here:
        sfondo.setIcon(ChaosDomain);
        setContentPane(sfondo);
    }//GEN-LAST:event_chaosActionPerformed

    private void NecronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NecronActionPerformed
        // TODO add your handling code here:
        sfondo.setIcon(NecronTombWorld);
        setContentPane(sfondo);
    }//GEN-LAST:event_NecronActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SchermataGioco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SchermataGioco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SchermataGioco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SchermataGioco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        GestoreGioco gamman = new GestoreGioco();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SchermataGioco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Necron;
    private javax.swing.JButton Tyranids;
    private javax.swing.JButton chaos;
    private javax.swing.JLabel personaggio;
    private javax.swing.JLabel sfondo;
    // End of variables declaration//GEN-END:variables
}
