/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gdrwarhammer40k;

import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author bernicchi.davide
 */
public class SchermataSchetaPersonaggio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SchermataSchetaPersonaggio.class.getName());

    /**
     * Creates new form SchermataSchetaPersonaggio
     */
    public SchermataSchetaPersonaggio() {
        initComponents();    
        
        
        ImageIcon iconAss = new javax.swing.ImageIcon(getClass().getResource("/imagini/Assoult.png"));
        Image scaledImgAss = iconAss.getImage().getScaledInstance(302, 239, Image.SCALE_SMOOTH);
    
        ImageIcon iconBull = new javax.swing.ImageIcon(getClass().getResource("/imagini/Bulwark.png"));
        Image scaledImgBull = iconBull.getImage().getScaledInstance(210, 232, Image.SCALE_SMOOTH);
    
        ImageIcon iconChap = new javax.swing.ImageIcon(getClass().getResource("/imagini/Chaplain.png"));
        Image scaledImgChap = iconChap.getImage().getScaledInstance(210, 280, Image.SCALE_SMOOTH);
    
        ImageIcon iconTer = new javax.swing.ImageIcon(getClass().getResource("/imagini/Terminator.png"));
        Image scaledImgTer = iconTer.getImage().getScaledInstance(180, 253, Image.SCALE_SMOOTH);
    
        
        this.setBackground(Color.black);
        this.AssoultButton.setIcon(new ImageIcon(scaledImgAss));
        this.BulWarkButton.setIcon(new ImageIcon(scaledImgBull));
        this.ChaplainButton.setIcon(new ImageIcon(scaledImgChap));
        this.TerminatorButton.setIcon(new ImageIcon(scaledImgTer));
        this.setContentPane(sfondo);
        sfondo.add(AssoultButton);
        sfondo.add(TerminatorButton);
        sfondo.add(ChaplainButton);
        sfondo.add(BulWarkButton);
        
        
                AssoultButton.setOpaque(false);
        AssoultButton.setContentAreaFilled(false);
        AssoultButton.setBorderPainted(false);
        AssoultButton.setFocusPainted(false);        
        
        TerminatorButton.setOpaque(false);
        TerminatorButton.setContentAreaFilled(false);
        TerminatorButton.setBorderPainted(false);
        TerminatorButton.setFocusPainted(false);        
        
        ChaplainButton.setOpaque(false);
        ChaplainButton.setContentAreaFilled(false);
        ChaplainButton.setBorderPainted(false);
        ChaplainButton.setFocusPainted(false);        
        
        BulWarkButton.setOpaque(false);
        BulWarkButton.setContentAreaFilled(false);
        BulWarkButton.setBorderPainted(false);
        BulWarkButton.setFocusPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sfondo = new javax.swing.JLabel();
        AssoultButton = new javax.swing.JButton();
        TerminatorButton = new javax.swing.JButton();
        ChaplainButton = new javax.swing.JButton();
        BulWarkButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AssoultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssoultButtonActionPerformed(evt);
            }
        });

        TerminatorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TerminatorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(TerminatorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ChaplainButton, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AssoultButton, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(sfondo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BulWarkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TerminatorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ChaplainButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                            .addComponent(AssoultButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(BulWarkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(sfondo)
                .addGap(207, 207, 207))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TerminatorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TerminatorButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TerminatorButtonActionPerformed

    private void AssoultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssoultButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AssoultButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SchermataSchetaPersonaggio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AssoultButton;
    private javax.swing.JButton BulWarkButton;
    private javax.swing.JButton ChaplainButton;
    private javax.swing.JButton TerminatorButton;
    private javax.swing.JLabel sfondo;
    // End of variables declaration//GEN-END:variables
}
