/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gdrwarhammer40k;

/**
 *
 * @author bernicchi.davide
 */
public class SchermataSchetaPersonaggio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SchermataSchetaPersonaggio.class.getName());

    /**
     * Creates new form SchermataSchetaPersonaggio
     */
    public SchermataSchetaPersonaggio() {
        initComponents();        
        sfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagini/schelta-personaggio.jpg")));
        this.AssoultButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagini/Assoult.png")));
        this.BulWarkButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagini/schelta-personaggio.jpg")));
        this.ChaplainButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagini/schelta-personaggio.jpg")));
        this.TerminatorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagini/Terminator.png")));
        this.setContentPane(sfondo);
        sfondo.add(AssoultButton);
        sfondo.add(TerminatorButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sfondo = new javax.swing.JLabel();
        AssoultButton = new javax.swing.JButton();
        TerminatorButton = new javax.swing.JButton();
        ChaplainButton = new javax.swing.JButton();
        BulWarkButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AssoultButton.setText("jButton1");

        TerminatorButton.setText("jButton2");

        ChaplainButton.setText("jButton3");

        BulWarkButton.setText("jButton4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sfondo)
                .addGap(138, 138, 138))
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ChaplainButton)
                    .addComponent(AssoultButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 399, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TerminatorButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BulWarkButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AssoultButton)
                    .addComponent(TerminatorButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 241, Short.MAX_VALUE)
                .addComponent(sfondo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChaplainButton)
                    .addComponent(BulWarkButton))
                .addGap(74, 74, 74))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SchermataSchetaPersonaggio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AssoultButton;
    private javax.swing.JButton BulWarkButton;
    private javax.swing.JButton ChaplainButton;
    private javax.swing.JButton TerminatorButton;
    private javax.swing.JLabel sfondo;
    // End of variables declaration//GEN-END:variables
}
