/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gdrwarhammer40k;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author 39340
 */
public class SchermataGioco extends javax.swing.JFrame {

    /**
     * Creates new form SchermataGioco
     */
    public SchermataGioco() {
        initComponents();
        ImageIcon icon = new ImageIcon("schermata-iniziale.png");
        sfondo.setIcon(icon);
        this.setContentPane(sfondo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sfondo = new javax.swing.JLabel();
        ButtonPodio = new javax.swing.JButton();
        ButtonInizia = new javax.swing.JButton();
        ButtonCarica = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sfondo.setText("jLabel1");

        ButtonPodio.setText("podio");
        ButtonPodio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPodioActionPerformed(evt);
            }
        });

        ButtonInizia.setText("inizia");
        ButtonInizia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonIniziaActionPerformed(evt);
            }
        });

        ButtonCarica.setText("carica");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(sfondo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(241, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonCarica)
                    .addComponent(ButtonInizia)
                    .addComponent(ButtonPodio))
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(ButtonPodio)
                .addGap(18, 18, 18)
                .addComponent(ButtonInizia)
                .addGap(18, 18, 18)
                .addComponent(ButtonCarica)
                .addGap(38, 38, 38)
                .addComponent(sfondo)
                .addGap(87, 87, 87))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonPodioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPodioActionPerformed
        // TODO add your handling code here:
        Podio pd = new Podio();
        pd.setVisible(true);
        
    }//GEN-LAST:event_ButtonPodioActionPerformed

    private void ButtonIniziaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonIniziaActionPerformed
        // TODO add your handling code here:
        SchermataInizio si = new SchermataInizio();
        si.setVisible(true);
    }//GEN-LAST:event_ButtonIniziaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SchermataGioco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SchermataGioco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SchermataGioco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SchermataGioco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SchermataGioco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCarica;
    private javax.swing.JButton ButtonInizia;
    private javax.swing.JButton ButtonPodio;
    private javax.swing.JLabel sfondo;
    // End of variables declaration//GEN-END:variables
}
