/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gdrwarhammer40k;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author 39340
 */
public class Schermata extends javax.swing.JFrame {

    /**
     * Creates new form SchermataGioco
     */
        GestoreGioco gg;
        FileManager fm;
    void setGG(GestoreGioco gegio){
        gg = gegio;
    }
    void setFileManager(FileManager faMa){
        fm = faMa;
    }
    public Schermata() {
        initComponents();
        //ImageIcon icon = new ImageIcon("sfondo-iniziale.png");
        sfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagini/sfondo-iniziale.png")));
        this.setContentPane(sfondo);
        sfondo.add(ButtonInizia);
        sfondo.add(ButtonCarica);
        ButtonCarica.setOpaque(false);
        ButtonCarica.setContentAreaFilled(false);
        ButtonCarica.setBorderPainted(false);
        ButtonCarica.setFocusPainted(false);
        ButtonInizia.setOpaque(false);
        ButtonInizia.setContentAreaFilled(false);
        ButtonInizia.setBorderPainted(false);
        ButtonInizia.setFocusPainted(false);
        
        ButtonCarica.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent e) {
                ButtonCarica.setText("{Carica}");
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent e) {
                ButtonCarica.setText("Carica");
            }
        });       
        ButtonInizia.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent e) {
                ButtonInizia.setText("{Inizia}");
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent e) {
                ButtonInizia.setText("Inizia");
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonInizia = new javax.swing.JButton();
        ButtonCarica = new javax.swing.JButton();
        sfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ButtonInizia.setFont(new java.awt.Font("Source Serif Pro Semibold", 0, 36)); // NOI18N
        ButtonInizia.setForeground(new java.awt.Color(255, 255, 204));
        ButtonInizia.setText("Inizia");
        ButtonInizia.setBorder(null);
        ButtonInizia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonIniziaActionPerformed(evt);
            }
        });

        ButtonCarica.setFont(new java.awt.Font("Source Serif Pro Semibold", 0, 36)); // NOI18N
        ButtonCarica.setForeground(new java.awt.Color(255, 255, 204));
        ButtonCarica.setText("Carica");
        ButtonCarica.setBorder(null);

        sfondo.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(sfondo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(885, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonCarica, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonInizia, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(271, Short.MAX_VALUE)
                .addComponent(ButtonInizia)
                .addGap(18, 18, 18)
                .addComponent(ButtonCarica)
                .addGap(92, 92, 92)
                .addComponent(sfondo)
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonIniziaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonIniziaActionPerformed
        // TODO add your handling code here:
        SchermataSchetaPersonaggio s = new SchermataSchetaPersonaggio();
        s.setGG(gg);
        s.setVisible(true);
        s.setSize(1039, 658);
    }//GEN-LAST:event_ButtonIniziaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Schermata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Schermata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Schermata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Schermata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Schermata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCarica;
    private javax.swing.JButton ButtonInizia;
    private javax.swing.JLabel sfondo;
    // End of variables declaration//GEN-END:variables
}
